### ISSUE TITLE
Unable to build project due to Jacoco and Firebase

### ISSUE THREAD

**Issue by johnjohndoe** [PSDev/DevDrawer#18]
I would like to build the project locally to try the latest development state. Currently, on the `compose` branch the `debug` build fails for me:

``` shell
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.dicedmelon.gradle:jacoco-android:0.1.5.
     Required by:
         project :
      > Could not resolve com.dicedmelon.gradle:jacoco-android:0.1.5.
         > Could not get resource 'https://jcenter.bintray.com/com/dicedmelon/gradle/jacoco-android/0.1.5/jacoco-android-0.1.5.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/dicedmelon/gradle/jacoco-android/0.1.5/jacoco-android-0.1.5.pom'.
               > Read timed out
```

You probably have the artifact cached locally. You might want to remove `jcenter()` which is [discontinued](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

``` shell
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
```

Could you please provide a debug build **without** Firebase or **no-op**?

**Comment by hameno** [comment]
Hi,
sorry but I won't work on a non-firebase version. I may update the dependency when I find the time to work on this again

**Comment by johnjohndoe** [comment]
I might be able to help with replacing the dependency if you like.

Not being able to build the project without a complete Firebase setup is quite unfortunate for an open source project, though.

**Comment by hameno** [comment]
Open-source does not mean that everybody needs to be easily able to build the project. Especially since this branch is a feature development and not part of the current release. Because of this I won't accept external contributions on that branch currently

**Comment by johnjohndoe** [comment]
What about `master`?
